serial:
  port: '/dev/ttyUSB0'

run:
  pause_time: 1
  sleep_time: 5

discharge_config:
  full_voltage: 12.8
  empty_voltage: 10.5

charge_config:
  float_current: 2.0
  full_voltage: 13.8
  boost_voltage: 14.4
  empty_voltage: 10.5

mqtt:
  hostname: '192.168.1.1'
  username: 'usr'
  password: 'passwd'