serial:
  port: '/dev/ttyUSB0'

run:
  pause_time: 1
  sleep_time: 5

invertor_config:
  full_voltage: 12.8
  empty_voltage: 10.5

mqtt:
  hostname: '192.168.1.1'
  username: 'usr'
  password: 'passwd'