serial:
  port: '/dev/ttyUSB0'

run:
  sleep_time: 2

discharge_config:
  full_voltage: 12.8
  empty_voltage: 10.5

charge_config:
  float_current: 6.0
  full_voltage: 13.6
  boost_voltage: 14.4
  empty_voltage: 10.5

energy: False

mqtt:
  hostname: '192.168.1.1'
  username: 'usr'
  password: 'passwd'